apiVersion: janus-idp.io/v1alpha1
kind: Backstage
metadata:
  name: my-backstage-app-with-app-config
spec:
  skipLocalDb: false
  application:
    appConfig:
      #mountPath:  /opt/app-root/src
      configMaps:
        - name: "my-backstage-config-cm1"
        - name: "my-backstage-config-cm2"
          key: "app-config1-cm2.gh.yaml"
    dynamicPluginsConfigMapName: "my-dynamic-plugins-config-cm"
    extraEnvs:
      envs:
        - name: MY_ENV_VAR_1
          value: my-value-1
        - name: MY_ENV_VAR_2
          value: my-value-2
      configMaps:
        - name: my-env-cm-1
        - name: my-env-cm-11
          key: CM_ENV11
      secrets:
        - name: my-env-secret1
        - name: my-env-secret11
          key: SEC_ENV11
    backendAuthSecret:
      name: "my-backstage-backend-auth-secret"
      key: "my-auth-key"
    replicas: 2
    extraFiles:
      mountPath: /tmp/my-extra-files
      configMaps:
        - name: "my-backstage-extra-config-cm1"
      secrets:
        - name: "my-backstage-extra-config-secret1"

---
apiVersion: v1
kind: Secret
metadata:
  name: my-backstage-backend-auth-secret
data:
  # generated with the command below (from https://janus-idp.io/docs/auth/service-to-service-auth/#setup):
  # node -p 'require("crypto").randomBytes(24).toString("base64")'
  backend-secret: TDRORDFRa2JxaFJhNTBzOGFDc1FWUEJ4ekFtRUw4UEU=
  my-auth-key: TDRORDFRa2JxaFJhNTBzOGFDc1FWUEJ4ekFtRUw4UEU=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-backstage-config-cm1
data:
  app-config1-cm1.db.yaml: |
    backend:
      database:
        connection:
          password: ${POSTGRESQL_PASSWORD}
          user: ${POSTGRESQL_USER}
  app-config2-cm1.yaml: |
    # Some comment in this file
  app-config3-cm1.odo.yaml: |
    catalog:
      locations:
        # [...]
        - type: url
          target: https://github.com/ododev/odo-backstage-software-template/blob/main/template.yaml
          rules:
            - allow: [Template]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-backstage-config-cm2
data:
  app-config1-cm2.gh.yaml: |
    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      environment: development
      providers:
        github:
          development:
            clientId: '${MY_ENV_VAR_1}'
            clientSecret: '${MY_ENV_VAR_2}'
  app-config2-cm2.yaml: |
    # a comment

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dynamic-plugins-config-cm
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: '@dfatwork-pkgs/scaffolder-backend-module-http-request-wrapped-dynamic@4.0.9-0'
        integrity: 'sha512-+YYESzHdg1hsk2XN+zrtXPnsQnfbzmWIvcOM0oQLS4hf8F4iGTtOXKjWnZsR/14/khGsPrzy0oq1ytJ1/4ORkQ=='
      - package: '@dfatwork-pkgs/explore-backend-wrapped-dynamic@0.0.9-next.11'
        integrity: 'sha512-/qUxjSedxQ0dmYqMWsZ2+OLGeovaaigRRrX1aTOz0GJMwSjOAauUUD1bMs56VPX74qWL1rf3Xr4nViiKo8rlIA=='
        pluginConfig:
          proxy:
            endpoints:
              /explore-backend-completed:
                target: 'http://localhost:7017'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-cm-1
data:
  CM_ENV1: "cm env 1"
  CM_ENV2: "cm env 2"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-cm-11
data:
  CM_ENV11: "cm env 11"
  CM_ENV12: "cm env 12"

---
apiVersion: v1
kind: Secret
metadata:
  name: my-env-secret1
stringData:
  SEC_ENV1: "secret env 1"
  SEC_ENV2: "secret env 2"

---
apiVersion: v1
kind: Secret
metadata:
  name: my-env-secret11
stringData:
  SEC_ENV11: "secret env 11"
  SEC_ENV12: "secret env 12"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-backstage-extra-config-cm1
data:
  cm_file1.txt: |
    # From ConfigMap
    Lorem Ipsum
    Dolor Sit Amet
  cm_file2.properties: |
    conf.x=y
    conf.y=z

---
apiVersion: v1
kind: Secret
metadata:
  name: my-backstage-extra-config-secret1
stringData:
  secret_file1.txt: |
    # From Secret
    Lorem Ipsum
    Dolor Sit Amet
  secret_file2.properties: |
    sec.a=b
    sec.b=c
  secrets.prod.yaml: |
    appId: 1
    webhookUrl: https://smee.io/foo
    clientId: someGithubAppClientId
    clientSecret: someGithubAppClientSecret
    webhookSecret: someWebhookSecret
    privateKey: |
      SomeRsaPrivateKey
