name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Lint
      run: make lint

    - name: Test
      run: make test

  container-image-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See ../Makefile for value of single arch PLATFORM used with targets docker-build and podman-build
        # NOTE: to build multiple arches, see ../Makefile and use target docker-buildx with PLATFORMS
        engine: [docker, podman]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: ${{ matrix.engine }}-build
        run: make ${{ matrix.engine }}-build

  release-build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install operator-sdk
        # Instructions from https://sdk.operatorframework.io/docs/installation/#install-from-github-release
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.33.0
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

      - name: release-build
        env:
          IMAGE_TAG_BASE: localhost:5000/janus-idp/operator
        run: make release-build
